minimal_test:
	g++ minimal_test.cpp -lboost_unit_test_framework -o minimal_test.o
boost_test_module:
	g++ boost_test_module.cpp -static -lboost_unit_test_framework -o boost_test_module.o 
boost_test_fixture:
	g++ boost_test_fixture.cpp -static -lboost_unit_test_framework -o boost_test_fixture.o
clean:
	rm -rf *.o